apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
        - name: sleeper
          image: busybox
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          command:
            - sh
            - -c
            - "sleep 100000"
